### ISSUE TITLE
3.1.1 Canvas

### ISSUE THREAD

**Issue by KmiArthur** [KmiArthur/Posconflictter#13]
**Descripción** 
Realizar CANVAS proyecto.

**Tareas a realizar:**

- [ ] Documento con el CANVAS del proyecto.

**Comment by jrsosago** [comment]
**Documento CANVAS** Tiempo empleado: 6 Horas. 
[Canvas - POSCONFLICTTER.pdf](https://github.com/KmiArthur/Posconflictter/files/1229690/Canvas.-.POSCONFLICTTER.pdf)

**Comment by jrsosago** [comment]
Se cierra está Issue por actividades realizadas.
