### ISSUE TITLE
2.1.1 Modelo Base de Datos

### ISSUE THREAD

**Issue by KmiArthur** [KmiArthur/Posconflictter#2]
**Descripción**
Modelo Base de Datos

**Tareas a realizar:**
- [x] Realizar Modelo Base de Datos no relacional
- [x] Mirar como guardar fotos en FireBase

**Comment by jrsosago** [comment]
Las tres entidades que se van a manejar en la Base de Datos son: Museum, Event y User
![image](https://user-images.githubusercontent.com/22827594/29640325-02c9a4ae-8824-11e7-988e-413dc7729761.png)

**Comment by jrsosago** [comment]
La entidad Event tiene la siguiente estructura:
![image](https://user-images.githubusercontent.com/22827594/29640541-fab0b14e-8824-11e7-91e9-8a310a462cae.png)

**Comment by jrsosago** [comment]
La entidad Museum, tiene la siguiente estructura.
![image](https://user-images.githubusercontent.com/22827594/29640815-3921ff72-8826-11e7-955d-2d3c0445b807.png)

**Comment by jrsosago** [comment]
La entidad User tiene la siguiente estructura:
![image](https://user-images.githubusercontent.com/22827594/29640981-13856578-8827-11e7-91ba-b610e0753176.png)

**Comment by jrsosago** [comment]
Las fotos se guardarán en FireBase, en la opción Storage.
![image](https://user-images.githubusercontent.com/22827594/29641465-4c19152c-8829-11e7-8da3-043dd94341da.png)

**Comment by jrsosago** [comment]
La entidad User se le quita un atributo, el cual es la contraseña, ya que fireBase hace la autenticación de la misma y no es necesario guardarla. Quedando de la siguiente manera.

![image](https://user-images.githubusercontent.com/22827594/30008759-365f481a-90e8-11e7-8641-5c9650b46c1a.png)

**Comment by jrsosago** [comment]
Se cierra Issue, por actividades completas.
