### ISSUE TITLE
1.3.1 Menú lateral

### ISSUE THREAD

**Issue by KmiArthur** [KmiArthur/Posconflictter#22]
**Descripción:**
Menú Lateral

**Tareas a realizar:**
- [x] Realizar Menú lateral con las siguientes opciones (Perfil Usuario, Calendario, Cerrar sesión)

**Comment by jrsosago** [comment]
Se cierra está Issue, ya que en la reunión del día miércoles 30 de Agosto se decidió que está barra no debía ir en la aplicación, por el cambio de está tarea se asigna la Issue #61
