### ISSUE TITLE
3.1.2 Logo y Nombre

### ISSUE THREAD

**Issue by jrsosago** [KmiArthur/Posconflictter#36]
**Descripción:**
Definir un nombre y un logo para la aplicación.

**Tareas a realizar:**
- [x] Definir nombre (Todos).
- [x] Definir logo (Todos).
- [x] Subir logo y cerrar Issue. @KmiArthur

**Comment by jrsosago** [comment]
# **Nombre de la aplicación:** Postconflictter.

**Comment by KmiArthur** [comment]
# Logo POSCONFLICTTER
![posconflictter logo](https://user-images.githubusercontent.com/17441569/29546154-2b8d1f78-86b8-11e7-8ec9-f74e18558626.png)
