### ISSUE TITLE
3.1.4 Mockups Aplicación

### ISSUE THREAD

**Issue by jrsosago** [KmiArthur/Posconflictter#37]
**Descripción**
Mockups Aplicación

**Tareas a realizar:**
- [x] Mockups de toda la aplicación

**Comment by KmiArthur** [comment]
![mockups posconflictter entrega 001](https://user-images.githubusercontent.com/17441569/29755631-7acc57dc-8b60-11e7-90bd-e2768da5f1dc.jpeg)
![mockups posconflictter entrega 002](https://user-images.githubusercontent.com/17441569/29755635-7aed71f6-8b60-11e7-90c3-ece49b452e70.jpeg)
![mockups posconflictter entrega 003](https://user-images.githubusercontent.com/17441569/29755636-7aefc35c-8b60-11e7-9ce8-f6ac85bc1fb2.jpeg)
![mockups posconflictter entrega 004](https://user-images.githubusercontent.com/17441569/29755632-7aec72b0-8b60-11e7-953e-0b76805f8ed6.jpeg)
![mockups posconflictter entrega 005](https://user-images.githubusercontent.com/17441569/29755634-7aed3b3c-8b60-11e7-8114-641f331c45dd.jpeg)
