### ISSUE TITLE
1.1.4 Restablecer contraseña

### ISSUE THREAD

**Issue by jrsosago** [KmiArthur/Posconflictter#61]
**Descripción:**
Restablecer contraseña, cuando el usuario la olvide.

**Tareas a realizar**

- [x] Restablecer contraseña del usuario.

**Comment by gsalvarez** [comment]
- Se elimina el campo contraseña en la base de datos ya que no se usa y no es necesaria.
- Se agrega la ventana para restablecer contraseña.
