### ISSUE TITLE
1.2.1 Nuevo evento

### ISSUE THREAD

**Issue by KmiArthur** [KmiArthur/Posconflictter#9]
**Descripción**
Crear un evento.

**Tareas a realizar:**

- [ ] Crear Nuevo evento: Nombre, Descripción, Fecha, Hora, Foto (opcional para el usuario), vídeos (opcional para el usuario), comentarios, puntuación.

**Comment by gsalvarez** [comment]
Se incluye el código para la creación de un evento en la Base de datos.
